In [4]:
import pandas as pd
import numpy as np
import tensorflow
import pickle
import tensorflow as tf
from tensorflow.keras.models import load_model

In [7]:
model = load_model("model.h5")

with open("one_hot_geo.pkl", "rb") as file:
    label_encoder_geo = pickle.load(file)

with open("label_encoder_gender.pkl", "rb") as file:
    label_encoder_gender = pickle.load(file)

with open("scaler.pkl", "rb") as file:
    scaler = pickle.load(file)

In [6]:
input_data = {
    "CreditScore": 600,
    "Geography": "France",
    "Gender": "Male",
    "Age": 40,
    "Tenure": 3,
    "Balance": 60000,
    "NumOfProducts": 2,
    "HasCrCard": 1,
    "IsActiveMember": 1,
    "EstimatedSalary": 50000,
}

In [8]:
geo_encoded = label_encoder_geo.transform([[input_data["Geography"]]]).toarray()

geo_encoded_df = pd.DataFrame(
    geo_encoded, columns=label_encoder_geo.get_feature_names_out(["Geography"])
)
geo_encoded_df

c:\Users\Uditya\.conda\envs\Udemy\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [9]:
input_data_df = pd.DataFrame([input_data])
input_data_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,600,France,Male,40,3,60000,2,1,1,50000

In [11]:
input_data_df["Gender"] = label_encoder_gender.transform(input_data_df["Gender"])
input_data_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,600,France,1,40,3,60000,2,1,1,50000

In [12]:
input_data_df = pd.concat(
    [input_data_df.drop("Geography", axis=1), geo_encoded_df], axis=1
)

In [13]:
input_data_df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,600,1,40,3,60000,2,1,1,50000,1.0,0.0,0.0

In [14]:
input_scaled = scaler.transform(input_data_df)
input_scaled

array([[-0.53598516,  0.91324755,  0.10479359, -0.69539349, -0.25781119,
         0.80843615,  0.64920267,  0.97481699, -0.87683221,  1.00150113,
        -0.57946723, -0.57638802]])

In [17]:
prediciton = model.predict(input_scaled)
prediciton

1/1 [==============================] - 0s 72ms/step

array([[0.03304451]], dtype=float32)