In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
import pickle

In [2]:
data = pd.read_csv("../01 Datasets\Churn_Modelling.csv")

In [3]:
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [4]:
data = data.drop(["RowNumber", "CustomerId", "Surname"], axis=1)

In [5]:
label_encoder_gender = LabelEncoder()
data["Gender"] = label_encoder_gender.fit_transform(data["Gender"])

In [6]:
onehot_encoder_geo = OneHotEncoder(handle_unknown="ignore")
geo_encoded = onehot_encoder_geo.fit_transform(data[["Geography"]]).toarray()
geo_encoded_df = pd.DataFrame(
    geo_encoded, columns=onehot_encoder_geo.get_feature_names_out(["Geography"])
)

In [7]:
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [8]:
data = pd.concat([data.drop("Geography", axis=1), geo_encoded_df], axis=1)
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [9]:
X = data.drop("EstimatedSalary", axis=1)
y = data["EstimatedSalary"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [10]:
with open("label_encoder_gender.pkl", "wb") as file:
    pickle.dump(label_encoder_gender, file)

with open("one_hot_geo.pkl", "wb") as file:
    pickle.dump(onehot_encoder_geo, file)

with open("scaler.pkl", "wb") as file:
    pickle.dump(scaler, file)

# ANN Regression Problem Statement

In [11]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

WARNING:tensorflow:From c:\Users\Uditya\.conda\envs\Udemy\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

In [13]:
model = Sequential([
    Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(32, activation='relu'),
    Dense(1)
])

In [14]:
model.compile(optimizer='adam', loss = 'mean_absolute_error', metrics=['mae'])

WARNING:tensorflow:From c:\Users\Uditya\.conda\envs\Udemy\Lib\site-packages\keras\src\optimizers\__init__.py:309: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

In [15]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_1 (Dense)             (None, 64)                832

 dense_2 (Dense)             (None, 32)                2080

 dense_3 (Dense)             (None, 1)                 33

=================================================================
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [20]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import warnings

warnings.filterwarnings("ignore")

In [21]:
## set up the Tensorboard
log_dir = "regressionlogs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")

tensorboard_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)

In [22]:
## set up EarlyStopping
early_stopping_callback = EarlyStopping(
    monitor="val_loss", patience=5, restore_best_weights=True
)

In [24]:
history = model.fit(
    X_train,
    y_train,
    validation_data=(X_test, y_test),
    epochs=100,
    callbacks=[tensorboard_callback, early_stopping_callback],
)

Epoch 1/100
WARNING:tensorflow:From c:\Users\Uditya\.conda\envs\Udemy\Lib\site-packages\keras\src\utils\tf_utils.py:492: The name tf.ragged.RaggedTensorValue is deprecated. Please use tf.compat.v1.ragged.RaggedTensorValue instead.

WARNING:tensorflow:From c:\Users\Uditya\.conda\envs\Udemy\Lib\site-packages\keras\src\engine\base_layer_utils.py:384: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

250/250 [==============================] - 7s 11ms/step - loss: 100378.2969 - mae: 100378.2969 - val_loss: 98520.0391 - val_mae: 98520.0391
Epoch 2/100
250/250 [==============================] - 2s 7ms/step - loss: 99621.9766 - mae: 99621.9766 - val_loss: 96989.7656 - val_mae: 96989.7656
Epoch 3/100
250/250 [==============================] - 2s 10ms/step - loss: 96924.1172 - mae: 96924.1172 - val_loss: 93050.6797 - val_mae: 93050.6797
Epoch 4/100
250/250 [==============================] - 2s 7ms/step - loss: 91619.6172 - mae: 91619.6172 - val_loss: 86460.0938 - val_mae: 86460.0938
Epoch 5/100
250/250 [==============================] - 1s 6ms/step - loss: 83887.0547 - mae: 83887.0547 - val_loss: 77961.9922 - val_mae: 77961.9922
Epoch 6/100
250/250 [==============================] - 2s 8ms/step - loss: 74808.8906 - mae: 74808.8906 - val_loss: 69049.7891 - val_mae: 69049.7891
Epoch 7/100
250/250 [==============================] - 3s 11ms/step - loss: 65974.6719 - mae: 65974.6719 - val_loss: 61314.9141 - val_mae: 61314.9141
Epoch 8/100
250/250 [==============================] - 1s 6ms/step - loss: 58854.9453 - mae: 58854.9453 - val_loss: 55691.7422 - val_mae: 55691.7422
Epoch 9/100
250/250 [==============================] - 1s 5ms/step - loss: 54219.7734 - mae: 54219.7734 - val_loss: 52541.8281 - val_mae: 52541.8281
Epoch 10/100
250/250 [==============================] - 1s 5ms/step - loss: 51754.2930 - mae: 51754.2930 - val_loss: 51194.6406 - val_mae: 51194.6406
Epoch 11/100
250/250 [==============================] - 1s 5ms/step - loss: 50717.6875 - mae: 50717.6875 - val_loss: 50790.9336 - val_mae: 50790.9336
Epoch 12/100
250/250 [==============================] - 1s 6ms/step - loss: 50329.9023 - mae: 50329.9023 - val_loss: 50656.6250 - val_mae: 50656.6250
Epoch 13/100
250/250 [==============================] - 2s 9ms/step - loss: 50156.4336 - mae: 50156.4336 - val_loss: 50611.1992 - val_mae: 50611.1992
Epoch 14/100
250/250 [==============================] - 1s 6ms/step - loss: 50071.4062 - mae: 50071.4062 - val_loss: 50574.4805 - val_mae: 50574.4805
Epoch 15/100
250/250 [==============================] - 1s 5ms/step - loss: 50007.1992 - mae: 50007.1992 - val_loss: 50544.3320 - val_mae: 50544.3320
Epoch 16/100
250/250 [==============================] - 2s 9ms/step - loss: 49959.3125 - mae: 49959.3125 - val_loss: 50526.4297 - val_mae: 50526.4297
Epoch 17/100
250/250 [==============================] - 2s 6ms/step - loss: 49920.0508 - mae: 49920.0508 - val_loss: 50502.6562 - val_mae: 50502.6562
Epoch 18/100
250/250 [==============================] - 2s 9ms/step - loss: 49886.6172 - mae: 49886.6172 - val_loss: 50484.6719 - val_mae: 50484.6719
Epoch 19/100
250/250 [==============================] - 2s 7ms/step - loss: 49857.2695 - mae: 49857.2695 - val_loss: 50465.6445 - val_mae: 50465.6445
Epoch 20/100
250/250 [==============================] - 2s 6ms/step - loss: 49831.8398 - mae: 49831.8398 - val_loss: 50449.0547 - val_mae: 50449.0547
Epoch 21/100
250/250 [==============================] - 2s 6ms/step - loss: 49803.6836 - mae: 49803.6836 - val_loss: 50438.3750 - val_mae: 50438.3750
Epoch 22/100
250/250 [==============================] - 2s 6ms/step - loss: 49779.4883 - mae: 49779.4883 - val_loss: 50424.5625 - val_mae: 50424.5625
Epoch 23/100
250/250 [==============================] - 2s 7ms/step - loss: 49761.7852 - mae: 49761.7852 - val_loss: 50410.7656 - val_mae: 50410.7656
Epoch 24/100
250/250 [==============================] - 2s 7ms/step - loss: 49741.9258 - mae: 49741.9258 - val_loss: 50399.8828 - val_mae: 50399.8828
Epoch 25/100
250/250 [==============================] - 2s 7ms/step - loss: 49721.5547 - mae: 49721.5547 - val_loss: 50395.8398 - val_mae: 50395.8398
Epoch 26/100
250/250 [==============================] - 2s 6ms/step - loss: 49705.5195 - mae: 49705.5195 - val_loss: 50390.0273 - val_mae: 50390.0273
Epoch 27/100
250/250 [==============================] - 2s 7ms/step - loss: 49696.4023 - mae: 49696.4023 - val_loss: 50381.9023 - val_mae: 50381.9023
Epoch 28/100
250/250 [==============================] - 2s 7ms/step - loss: 49673.9805 - mae: 49673.9805 - val_loss: 50367.7773 - val_mae: 50367.7773
Epoch 29/100
250/250 [==============================] - 2s 7ms/step - loss: 49662.5391 - mae: 49662.5391 - val_loss: 50358.6328 - val_mae: 50358.6328
Epoch 30/100
250/250 [==============================] - 1s 5ms/step - loss: 49647.9570 - mae: 49647.9570 - val_loss: 50356.6445 - val_mae: 50356.6445
Epoch 31/100
250/250 [==============================] - 1s 5ms/step - loss: 49637.5312 - mae: 49637.5312 - val_loss: 50351.5664 - val_mae: 50351.5664
Epoch 32/100
250/250 [==============================] - 1s 5ms/step - loss: 49622.4688 - mae: 49622.4688 - val_loss: 50345.0469 - val_mae: 50345.0469
Epoch 33/100
250/250 [==============================] - 1s 4ms/step - loss: 49613.8789 - mae: 49613.8789 - val_loss: 50338.6875 - val_mae: 50338.6875
Epoch 34/100
250/250 [==============================] - 1s 5ms/step - loss: 49598.7305 - mae: 49598.7305 - val_loss: 50344.5312 - val_mae: 50344.5312
Epoch 35/100
250/250 [==============================] - 1s 5ms/step - loss: 49589.7305 - mae: 49589.7305 - val_loss: 50342.6289 - val_mae: 50342.6289
Epoch 36/100
250/250 [==============================] - 1s 4ms/step - loss: 49583.0977 - mae: 49583.0977 - val_loss: 50336.9922 - val_mae: 50336.9922
Epoch 37/100
250/250 [==============================] - 1s 4ms/step - loss: 49568.7812 - mae: 49568.7812 - val_loss: 50336.4453 - val_mae: 50336.4453
Epoch 38/100
250/250 [==============================] - 1s 5ms/step - loss: 49559.0039 - mae: 49559.0039 - val_loss: 50329.6641 - val_mae: 50329.6641
Epoch 39/100
250/250 [==============================] - 1s 4ms/step - loss: 49555.1523 - mae: 49555.1523 - val_loss: 50339.8008 - val_mae: 50339.8008
Epoch 40/100
250/250 [==============================] - 2s 7ms/step - loss: 49542.6445 - mae: 49542.6445 - val_loss: 50335.7930 - val_mae: 50335.7930
Epoch 41/100
250/250 [==============================] - 2s 6ms/step - loss: 49534.4922 - mae: 49534.4922 - val_loss: 50342.1367 - val_mae: 50342.1367
Epoch 42/100
250/250 [==============================] - 1s 5ms/step - loss: 49531.2031 - mae: 49531.2031 - val_loss: 50335.1680 - val_mae: 50335.1680
Epoch 43/100
250/250 [==============================] - 1s 6ms/step - loss: 49522.1445 - mae: 49522.1445 - val_loss: 50325.8203 - val_mae: 50325.8203
Epoch 44/100
250/250 [==============================] - 1s 5ms/step - loss: 49513.6406 - mae: 49513.6406 - val_loss: 50322.5195 - val_mae: 50322.5195
Epoch 45/100
250/250 [==============================] - 1s 4ms/step - loss: 49508.0977 - mae: 49508.0977 - val_loss: 50323.7617 - val_mae: 50323.7617
Epoch 46/100
250/250 [==============================] - 1s 5ms/step - loss: 49499.8984 - mae: 49499.8984 - val_loss: 50329.9688 - val_mae: 50329.9688
Epoch 47/100
250/250 [==============================] - 1s 5ms/step - loss: 49492.9453 - mae: 49492.9453 - val_loss: 50317.3164 - val_mae: 50317.3164
Epoch 48/100
250/250 [==============================] - 1s 5ms/step - loss: 49487.4609 - mae: 49487.4609 - val_loss: 50318.0781 - val_mae: 50318.0781
Epoch 49/100
250/250 [==============================] - 1s 4ms/step - loss: 49480.4531 - mae: 49480.4531 - val_loss: 50332.4766 - val_mae: 50332.4766
Epoch 50/100
250/250 [==============================] - 1s 5ms/step - loss: 49476.5547 - mae: 49476.5547 - val_loss: 50332.3477 - val_mae: 50332.3477
Epoch 51/100
250/250 [==============================] - 1s 4ms/step - loss: 49471.1172 - mae: 49471.1172 - val_loss: 50332.4961 - val_mae: 50332.4961
Epoch 52/100
250/250 [==============================] - 1s 4ms/step - loss: 49462.6797 - mae: 49462.6797 - val_loss: 50335.8906 - val_mae: 50335.8906

In [25]:
%load_ext tensorboard

In [29]:
%tensorboard --logdir regressionlogs/fit

Reusing TensorBoard on port 6006 (pid 1396), started 0:00:07 ago. (Use '!kill 1396' to kill it.)

In [30]:
test_loss, test_mae = model.evaluate(X_test, y_test)
print(f'Test MAE: {test_mae}')

63/63 [==============================] - 0s 3ms/step - loss: 50317.3164 - mae: 50317.3164
Test MAE: 50317.31640625

In [31]:
model.save('regressionmodel.h5')